backend:
  name: github
  repo: Alialbarg000/Alialbarg000.github.io
  branch: main
  identity_url: "https://sansoonyachtservices.netlify.app/.netlify/identity"

media_folder: "images" # Where uploaded images will go
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Main Body Text", name: "body", widget: "markdown" }
